'''
Created on Dec 16, 2011

@author: jianhuashao
'''

TOKEN_KEY = "token_key"
CALLBACK = "callback"
METHOD = "method"
TARGET = "target"
BODY = "body"
TOKEN = "token"

ACTION = "action"

#ACTION_TYPE_REGISTER_REQUEST = "request"
#ACTION_TYPE_REGISTER_AUTHORIZE = "authorize"
ACTION_TYPE_REGISTER = "register"
ACTION_TYPE_MANAGE = "manage"
ACTION_TYPE_ACCESS = "access"

ACTION_PARAM = "action_params"

REGISTER_SOURCE = "source"
REGISTER_SOURCE_TOKEN = "token"
REGISTER_SOURCE_RESOURCE = "resource"

REGISTER_STATUS = "status"
REGISTER_STATUS_INIT = "init"
REGISTER_STATUS_REQUEST = "request"
REGISTER_STATUS_AUTHORIZE = "authorize"
REGISTER_BODY = BODY
'''REGISTER_RESOURCE_NAME = "name"
REGISTER_RESOURCE_URL = "url"
REGISTER_RESOURCE_DESCRIPTION = "description"
REGISTER_RESOURCE_CALLBACK = CALLBACK
REGISTER_RESOURCE_METHOD = METHOD
REGISTER_RESOURCE_TARGET = TARGET'''
REGISTER_INIT_OBJECT_TYPE = "type"
REGISTER_INIT_OBJECT_TYPE_RESOURCE = "resource"
REGISTER_INIT_OBJECT_TYPE_TOKEN = "token"
REGISTER_INIT_OBJECT_RESOURCE = "url"
REGISTER_INIT_OBJECT_TOKEN = "token"
REGISTER_INIT_OBJECT_NAME = "name"
REGISTER_INIT_OBJECT_ALIAS = "alias"
REGISTER_INIT_OBJECT_PERMISSION = "permission"
REGISTER_INIT_OBJECT_PERMISSION_MANAGE = "manage"
REGISTER_INIT_OBJECT_PERMISSION_ACCESS = "access"
REGISTER_INIT_OBJECT_DESCRIPTION = "description"
REGISTER_REQUEST_SOURCE = "source"
REGISTER_REQUEST_TARGET = "target"
REGISTER_REQUEST_OPERATION = "operation"
REGISTER_REQUEST_OPERATION_MANAGE = "manage"
REGISTER_REQUEST_OPERATION_ACCESS = "access"
REGISTER_REQUEST_STATUS = "status"
REGISTER_REQUEST_STATUS_REQUEST = "request"
REGISTER_REQUEST_STATUS_AUTHORIZE = "authorize"
REGISTER_REQUEST_STATUS_ACCESS = "access"
REGISTER_REQUEST_STATUS_FINISH = "finish"
'''REGISTER_REQUEST_TOKEN_KEY = TOKEN_KEY
REGISTER_REQUEST_CALLBACK = CALLBACK
REGISTER_REQUEST_METHOD = METHOD
REGISTER_REQUEST_TARGET = TARGET'''
REGISTER_AUTHORIZE_TOKEN_KEY = TOKEN

MANAGE_OPERATION = "operation"
MANAGE_OPERATION_METADATA = "metadata"
MANAGE_OPERATION_SETTING = "setting"
MANAGE_OPERATION_BILL = "bill"
MANAGE_OPERATION_FEEDBACK = "feedback"
MANAGE_OPERATION_INQUIRY = "inquiry"
MANAGE_BODY = BODY
MANAGE_TOKEN_KEY = TOKEN_KEY
MANAGE_CALLBACK = CALLBACK
MANAGE_METHOD = METHOD
MANAGE_TARGET = TARGET

ACCESS_TYPE = "type"
ACCESS_TYPE_1 = 1
ACCESS_TYPE_2 = 2
ACCESS_TYPE_3 = 3
ACCESS_BODY = BODY
ACCESS_TOKEN = TOKEN_KEY
ACCESS_QUERY = "query"
ACCESS_VALIDATION = "validation"
ACCESS_CAPABILITY = "capability"
ACCESS_BODY_DATA = "data"
ACCESS_ACCESS_TOKEN = "access_token"
ACCESS_RESULT = "access_result"
'''ACCESS_CALLBACK = CALLBACK
ACCESS_METHOD = METHOD
ACCESS_TARGET = TARGET
ACCESS_BODY_TOKEN_KEY = TOKEN_KEY
ACCESS_BODY_TIMESTAMP = "timestamp"
'''

CALLBACK = "callback"
CALLBACK_URL = "url"
CALLBACK_METHOD = "method"
CALLBACK_METHOD_POST = "POST"
CALLBACK_METHOD_GET = "GET"
